### ISSUE TITLE
English please 

### ISSUE THREAD

**Issue by Jeffbe232** [raypo/eml2csv#1]
Can’t make this app work, the tutorial is in a language other than English.  If I had known this I would not have bought it

**Comment by raypo** [comment]
Sorry for the inconvenience.
If you got the eml files ,you can just [import](https://support.apple.com/guide/itunes/transfer-files-itns32636/windows) to the eml2csv App . Then you can parse the eml files.  
If you has not got the eml files the App need, you need export the eml files first to use this App .

**Comment by Jeffbe232** [comment]
This is not all that helpful because I don’t know how to import to the app.  Please disregard, no need to further respond.  I will just delete the app
